version: "3.5"

networks:
  data:
    driver: bridge

services:
  vm-agt:
    image: victoriametrics/vmagent
    container_name: vm-agt
    hostname: vm-agt
    restart: always
    stop_grace_period: 5m
    networks:
      - net
    ports:
      - 8429:8429/tcp
      - 8189:8189/tcp
    volumes:
      - ./cfg/vmagent_prometheus.yml:/vmagent_prometheus.yml
      - ./data/vmagt:/storage
    command:
      - "-promscrape.config=/vmagent_prometheus.yml"
      - "-remoteWrite.tmpDataPath=/storage"
      - "-loggerLevel=INFO"
      - "-httpListenAddr=:8429"
      - "-influxListenAddr=:8189"
      - "-influxSkipSingleField"
      - "-remoteWrite.showURL"
      - "-remoteWrite.url=http://vm:8428/api/v1/write"
      - "-remoteWrite.url=https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
      - "-remoteWrite.basicAuth.username=USRID"
      - "-remoteWrite.basicAuth.password=TOKEN"
  vm:
    image: victoriametrics/victoria-metrics:latest
    container_name: vm
    hostname: vm
    restart: always
    stop_grace_period: 5m
    networks:
      - data
    ports:
      - 8428:8428/tcp
    volumes:
      - ./data/vm:/data
    command:
      - "-storageDataPath=/data"
      - "-loggerLevel=INFO"
      - "-loggerFormat=default"
      - "-httpListenAddr=:8428"
      - "-retentionPeriod=2y"
      - "-influxSkipSingleField"
      - "-selfScrapeInterval=30s"
      - "-inmemoryDataFlushInterval=15s"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    networks:
      - data
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=flant-statusmap-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./cfg/grafana/provisioning/:/etc/grafana/provisioning/
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - vm
      - loki
  hubitat_exporter:
    image: syepes/hubitat_exporter:latest
    container_name: hubitat_exporter
    hostname: hubitat_exporter
    restart: always
    stop_grace_period: 3s
    networks:
      - net
    ports:
      - 8000:8000/tcp
    environment:
      - HE_IP=ABC
      - HE_APP_ID=ABC
      - HE_API_TOKEN=ABC
      - HE_AUTH_USR=ABC
      - HE_AUTH_PWD=ABC
      - HE_DD=true
